name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          cd backend/fastapi
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backend tests
        run: echo "Add tests here"

  windows-build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r agents/windows-agent/requirements.txt
      - name: package
        run: echo "Add PyInstaller build steps here"

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r agents/linux-agent/requirements.txt
      - name: package
        run: echo "Add deb packaging steps here"
